[command.add]
short = "Add resource"
long = "Add specific resource"

link_use = "link [LINK_NAME]"
link_short = "Declare a link"
link_long = "Declare a link here without any value"
link_add_success = "Declared a new link: {{ .LinkName }}"

lkv_use = "tag LINK_NAME TAG PATH"
lkv_short = "Add a tag to a link"
lkv_long = "Add a value to a link(you have to declare it first). Please pay attention to the spaces in the `PATH`, use double comma to wrap the `PATH` to if you have so."

bind_use = "bind LINK_NAME:TAG TARGET_LINK_NAME:TARGET_TAG"
bind_short = "Bind two links in one-way"
bind_long = "Bind two links in one-way. When you switched to `[LINK_NAME]:[TAG]`, we will automatically switch to `[TARGET_LINK_NAME]:[TARGET_TAG]`"
bind_success = "Bind success: {{ .SrcName }}:{{ .SrcTag }} ==> {{ .TargetName }}:{{ .TargetTag }}"

[command.delete]
short = "Delete resource"
long = "Delete specific resource"

link_use = "link [LINK_NAME]"
link_short = "Delete link declaration"

lkv_use = "tag LINK_NAME [TAG]"
lkv_short = "Delete a link value"
lkv_long = "Delete a link value. Delete all the values if you don't specific TAG"

bind_use = "bind LINK_NAME:TAG TARGET_LINK_NAME:TARGET_TAG"
bind_short = "Delete bind"

[command.get]
short = "List specific resource"

links_short = "List all link declarationes"

lkv_use = "tags [LINK_NAME]"
lkv_short = "List all the values in a link."

bind_use = "bind ([LINK_NAME] [TAG])"
bind_short = "List all the binds"

using_short = "Get current using binds"

[command.root]
short = "symbolic-link-manager is a tool to manage symbolic link in your system"
long ="""
A tool to manage symbolic link, usually used to switch SDK version.

Full documentation: https://github.com/IceOfSummer/symbolic-link-manager
"""

[command.update]
short = "Update resource"
long = "Update specific resource"

link_use = "link LINK_NAME"
link_short = "Update link declaration"

lkv_use = "tag LINK_NAME TAG"
lkv_short = "Update link value"

bind_use = "bind LINK_NAME:TAG TARGET_LINK_NAME:TARGET_TAG"
bind_short = "Update bind"

[command.update.flag]
name = "The new name"
path = "The new path"
tag = "The new tag"

[command.use]
use = "use LINK_NAME TAG"
short = "Use specific link"
success = "Switched: {{ .LinkName }}:{{ .Tag }}"

[error]
noenv = "Please setup environment variabled `SLINK_MANAGER_HOME` before you using"
invalid_name_mark_pair = "Failed to parse `{{ .Raw }}`, it contains multiply `:`!"
no_such_link = "Can't find corresponding link declaration: {{ .LinkName }}"
no_such_link_value = "No such tag: {{ .LinkName }}:{{ .Tag }}"
no_such_bind = "No such bind"


[message]
update_success = "Update success"
delete_success_prefix = "Deleted: "
nothing_changed = "Nothing changed"
nothing_found = "Nothing found"
delete_link_delaration_success = "Link declaration deleted: {{ .LinkName }}"
