name: CI checks

on:
  push:
    branches:
      - master
  pull_request:
    types: [ synchronize, opened ]
    branches:
      - master
jobs:
  ci:
    runs-on: ubuntu-latest
    name: 'Run CI'
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Test
        id: test
        run: go test -v ./...

    outputs:
      test_success: ${{ steps.test.conclusion }}

  add_label_for_pr:
    name: 'Add Label For Pull Request'
    needs: ci
    if: ${{ always() && github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Clear old label
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'remove-labels'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          labels: 'test:success, test:failed'
      - name: Add label
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-labels'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          labels: >
            ${{ needs.ci.outputs.test_success == 'success' && 'test:success' || 'test:failed' }}